model_name: vecformer
model_args:
  instance_criterion_config:
    class_loss_weight: 2.5
    ce_non_object_weight: 0.01
    bce_loss_weight: 5.0
    dice_loss_weight: 5.0
    score_loss_weight: 0.5
    topk_matches: 1
    iter_matcher: true
    label_smoothing: 0.1
    bce_label_smoothing: 0.0
    use_mean_batch_loss: true
  semantic_criterion_config:
    ce_loss_weight: 5.0
    ce_unlabeled_weight: 0.1
    label_smoothing: 0.0
    use_mean_batch_loss: true